Refactor(hyunsoo/chat): 채팅 기능 리팩터링 #92
modern-agile-team/4term-main-back pull request #249
Opened 2023-01-10 08:47 UTC by Kimsoo0119

2023-01-11 08:55 UTC, khabh commented on main-project/src/chats/interface/chat.interface.ts
>  export interface PreviousChatLog {
삭제해 주세요

2023-01-12 05:05 UTC, khabh requested changes

2023-01-12 05:05 UTC, khabh commented on main-project/src/chats/repository/chat-list.repository.ts
> +      const chatRoom = await this.createQueryBuilder('chat_list')
```suggestion
      const chatRoom :  ChatList = await this.createQueryBuilder('chat_list')
```

2023-01-12 05:08 UTC, klaus9267 commented on main-project/src/chats/dto/accept-invitation.dto.ts
>    @IsNotEmpty()
dto에서 데코레이터의 우선순위는 
트랜스퍼 벨리데이트 -> 클래스 벨리데이트 순으로 실행되고
또 아래에서 위로 실행됩니다 그래서
```
@IsNumber()
@IsNotEmpty()
```
로 변경해주시는 좋을 것 같아요 :)

2023-01-12 05:09 UTC, klaus9267 commented on main-project/src/chats/dto/get-chat-log.dto.ts
>    @ApiProperty({
example후에 description도 작성해주세요!

2023-01-12 05:11 UTC, klaus9267 commented on main-project/src/chats/interface/chat.interface.ts
>    chatRoomNo: number;
userNo, chatRoomNo를 사용하는 다른 interface도 보이는데 후에 리팩터링 할 때 상속을 사용해주시면 더 좋은 코드가 될 것 같아요 :)

2023-01-12 05:15 UTC, klaus9267 commented on main-project/src/chats/repository/chat-list.repository.ts
>        const result = await this.createQueryBuilder('chat_list')
```suggestion
      const result : ChatRoomUser = await this.createQueryBuilder('chat_list')
```

2023-01-12 05:25 UTC, klaus9267 commented on main-project/src/chats/chats-controller.service.ts
>      inviteUser: InviteUserDTO,
inviteUser를 아래 코드에서 자체적으로 쓰는 곳은 없는 것 같은데
그럼 매개변수 자체에서 펼쳐주시는게 줗을 것 같아요!
```suggestion
 { userNo, targetUserNo }: InviteUserDTO
```

2023-01-12 13:53 UTC, merged